// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Refines product and category descriptions into targeted search queries for identifying purchase intent signals.
 *
 * - refineSearchQueries - A function that refines the search queries.
 * - RefineSearchQueriesInput - The input type for the refineSearchQueries function.
 * - RefineSearchQueriesOutput - The return type for the refineSearchQueries function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineSearchQueriesInputSchema = z.object({
  productDescription: z.string().describe('The description of the product of interest.'),
  category: z.string().describe('The category the product belongs to.'),
});
export type RefineSearchQueriesInput = z.infer<typeof RefineSearchQueriesInputSchema>;

const RefineSearchQueriesOutputSchema = z.object({
  refinedQueries: z.array(z.string()).describe('An array of refined search queries optimized for identifying purchase intent signals.'),
});
export type RefineSearchQueriesOutput = z.infer<typeof RefineSearchQueriesOutputSchema>;

export async function refineSearchQueries(input: RefineSearchQueriesInput): Promise<RefineSearchQueriesOutput> {
  return refineSearchQueriesFlow(input);
}

const refineSearchQueriesPrompt = ai.definePrompt({
  name: 'refineSearchQueriesPrompt',
  input: {schema: RefineSearchQueriesInputSchema},
  output: {schema: RefineSearchQueriesOutputSchema},
  prompt: `You are an expert in B2B sales and marketing. Your task is to refine search queries to identify potential customers who are likely to purchase a product.

  Given a product description and category, generate a list of search queries that would help identify users with high purchase intent. Consider signals like:
  - Keyword searches related to buying the product
  - Competitor searches
  - Company visitation patterns on relevant websites
  - Duration and depth of site visits
  - New hiring for product decision makers
  - Demo requests
  - Pricing requests

  Product Description: {{{productDescription}}}
  Category: {{{category}}}

  Refined Queries:`, // Ensure the LLM returns only the refined queries in the array format.
});

const refineSearchQueriesFlow = ai.defineFlow(
  {
    name: 'refineSearchQueriesFlow',
    inputSchema: RefineSearchQueriesInputSchema,
    outputSchema: RefineSearchQueriesOutputSchema,
  },
  async input => {
    const {output} = await refineSearchQueriesPrompt(input);
    return output!;
  }
);
